[package]
name = "reports"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
image = "0.25.2"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
